image: ilaborie/hugonode

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - hugo version
  - echo node `node --version`
  - echo yarn `yarn --version`
  - pushd themes/devfest-theme-hugo
  - yarn
  - popd

sandbox:
  script:
    - npn run build:pdf
    - hugo -F
    - npn run build:minify
    - firebase use default
    - firebase deploy --token "$FIREBASE_SANDBOX_TOKEN"
  artifacts:
    paths:
      - public
  only:
    - develop

prod:
  variables:
    HUGO_ENV: production
  script:
    - npn run build:pdf
    - hugo --baseURL https://2019.devfesttoulouse.fr/
    - npn run build:minify
    - firebase use prod
    - firebase deploy --token "$FIREBASE_PROD_TOKEN"
  artifacts:
    paths:
      - public
  only:
    - master
